### ISSUE TITLE
AbsurdJS - Hacking the front-end

### ISSUE THREAD

**Issue by krasimir** [RisingStack/oneshot-budapest#18]
It's a talk about [AbsurdJS](https://github.com/krasimir/absurd) ([http://absurdjs.com/](http://absurdjs.com/)). JavaScript library that acts as a CSS and HTML preprocessor. At the same time is a template engine and client-side framework. The presentation is made of two parts. The first one presents the library and the second one is the real life project that uses it.

**Comment by gergelyke** [comment]
We are looking for Node talks, not frontend ones.

**Comment by krasimir** [comment]
Hi,

actually the title of the talk is a little bit misleading. AbsurdJS is a Node.js module. It is a CSS preprocessor and could be used as HTML template engine. I admit, indeed the talk is partly about the front-end port of the library. 

Anyway, thanks for the answer. I just saw that the lineup is almost filled up with great Node.js related talks and I'm sure that the conference will be awesome.
