### ISSUE TITLE
Improving App Performance and Business Intelligence

### ISSUE THREAD

**Issue by rosskukulinski** [RisingStack/oneshot-budapest#27]
### If you can't measure it, don't "improve" it

This will be a revamped version of a talk I did at [BayNode](http://www.meetup.com/BayNode/) last [December](http://www.meetup.com/BayNode/events/150715452/).

David Knuth wrote, "Programmers waste enormous amounts of time thinking about, or worrying about, the speed of noncritical parts of their programs, and these attempts at efficiency actually have a strong negative impact when debugging and maintenance are considered. We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil. Yet we should not pass up our opportunities in that critical 3%."

In this talk, I will cover what metrics are, why developers should use them as soon as their application starts to take shape, and how to get create a simple metrics aggregation and analytics system with [StatsD](https://github.com/etsy/statsd/), [Graphite](http://graphite.readthedocs.org/en/latest/), and [Grafana](http://grafana.org/).

I will be drawing from real-life examples from my experiences building NodeJS applications for Military and Commercial Aviation Training as well as lessons learned building SpeakIt.io, a collaborative realtime voice communication platform.

[Original Blog Post](http://kukulinski.com/nodejs-metrics-with-statsd-and-graphite/)
[Original Slides](http://rosskukulinski.github.io/talk-statsd/#/)

**Comment by rosskukulinski** [comment]
(minor edits)

**Comment by dscape** [comment]
Omg would be amazing to meet you @rosskukulinski !

**Comment by rosskukulinski** [comment]
awww shucks, @dscape
