### ISSUE TITLE
Fun with AirPlay

### ISSUE THREAD

**Issue by watson** [RisingStack/oneshot-budapest#4]
I was frustrated there was no free, open source AirPlay servers available, so I started to build my own for Node. In the process I discovered that the current public knowledge of the underlying protocols are lacking and started [a project to reverse engineer](http://watson.github.io/airharvest/) them.

I'll be showing what I've learned and be demoing some of the fun things you can do when you run an AirPlay server in Node.

**Comment by oroce** [comment]
Hey our cfp is closed now, but we are doing a preevent meetup on Wednesday: http://www.meetup.com/nodebp/events/216529672/

Don't you wanna do this talk at nodebp?

**Comment by watson** [comment]
I would love to, but I'm not going to make it unfortunately since I decided to stay a little bit in Australia after campjs

**Comment by oroce** [comment]
okay have a great time in Australia:-)
